export const copy = {
  en: {
    eyebrow: 'YOUR FILES, YOUR MEMORY',
    onboardingTitle: 'Give the web a local address.',
    settingsTitle: 'LocalKeepFlash settings',
    intro:
      'LocalKeepFlash writes readable Markdown into a folder you choose. There is no account, cloud database, analytics, or AI service in the middle.',
    permissionTitle: 'Why it can read websites',
    permissionBody:
      'Website access is used only after you save, so the extension can extract the page and copy its images. Nothing is sent to KeepFlash or another service.',
    folderTitle: 'Choose your archive',
    folderBody:
      'This can be a normal folder, an Obsidian vault, or a directory synced by software you already trust.',
    chooseFolder: 'Choose folder',
    changeFolder: 'Change folder',
    noFolder: 'No folder selected',
    permissionReady: 'Write access ready',
    permissionMissing: 'Permission needs attention',
    languageTitle: 'Transcript languages',
    languageBody: 'LocalKeepFlash tries these languages in order, preferring human captions over automatic captions.',
    finish: 'Finish setup',
    saveSettings: 'Save settings',
    next: 'Continue',
    back: 'Back',
    readyTitle: 'Your archive is ready.',
    readyBody: 'Click the toolbar icon to save a page, or use the right-click menu for a selection or image.',
    saved: 'Settings saved',
    testFailed: 'The folder could not be written. Choose it again and grant write access.',
    folderPrivacy: 'Only the browser stores this folder permission. Files remain on your device.',
    step: 'Step',
  },
  zh: {
    eyebrow: '你的文件，你的记忆',
    onboardingTitle: '给网页一个本地地址。',
    settingsTitle: 'LocalKeepFlash 设置',
    intro: 'LocalKeepFlash 将可读的 Markdown 写入你选择的目录。中间没有账号、云数据库、数据分析或 AI 服务。',
    permissionTitle: '为什么需要读取网页',
    permissionBody: '只有在你主动保存时，扩展才会读取当前页面、提取正文并复制图片。内容不会发送给 KeepFlash 或其他服务。',
    folderTitle: '选择你的资料库',
    folderBody: '可以是普通目录、Obsidian 仓库，或由你信任的软件负责同步的目录。',
    chooseFolder: '选择目录',
    changeFolder: '更换目录',
    noFolder: '尚未选择目录',
    permissionReady: '写入权限正常',
    permissionMissing: '需要恢复权限',
    languageTitle: '字幕语言',
    languageBody: 'LocalKeepFlash 将按顺序尝试这些语言，并优先选择人工字幕。',
    finish: '完成初始化',
    saveSettings: '保存设置',
    next: '继续',
    back: '返回',
    readyTitle: '你的本地资料库已准备好。',
    readyBody: '点击工具栏图标保存整页，或使用右键菜单保存选区和图片。',
    saved: '设置已保存',
    testFailed: '无法写入该目录，请重新选择并允许写入。',
    folderPrivacy: '目录权限只保存在当前浏览器中，文件始终留在你的设备上。',
    step: '步骤',
  },
} as const;
